export type FlowKind='cyan'|'amber'|'violet';
export type OperatorKind='switch'|'filter'|'alternator'|'priority';
export type Node={id:number;x:number;y:number;links:number[];sink?:FlowKind;source?:FlowKind};
export type Operator={id:number;kind:OperatorKind;node:number;orientation:number;memory:number};
export type Packet={id:number;kind:FlowKind;node:number;from:number|null;next:number|null;progress:number;wait:number};
export type SignalState={seed:number;time:number;duration:number;nodes:Node[];operators:Operator[];packets:Packet[];spawned:number;delivered:number;lost:number;pressure:Record<number,number>;outcome:'playing'|'won'|'lost';nextPacketId:number};
const kinds:FlowKind[]=['cyan','amber','violet'];
function rng(seed:number){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296);}
function layout(seed:number){const r=rng(seed),mirror=r()>.5,pts=[[.08,.18],[.08,.5],[.08,.82],[.27,.28],[.27,.7],[.47,.18],[.47,.5],[.47,.82],[.67,.3],[.67,.7],[.88,.18],[.88,.5],[.88,.82]],edges=[[0,3],[1,3],[1,4],[2,4],[3,5],[3,6],[4,6],[4,7],[5,8],[6,8],[6,9],[7,9],[8,10],[8,11],[9,11],[9,12],[5,6],[6,7]];const nodes:Node[]=pts.map((p,i)=>({id:i,x:mirror?1-p[0]:p[0],y:p[1],links:[]}));for(const[a,b]of edges){nodes[a].links.push(b);nodes[b].links.push(a);}const sources=mirror?[10,11,12]:[0,1,2],sinks=mirror?[0,1,2]:[10,11,12];sources.forEach((n,i)=>nodes[n].source=kinds[i]);const sinkKinds=[...kinds].sort(()=>r()-.5);sinks.forEach((n,i)=>nodes[n].sink=sinkKinds[i]);const slots=[3,4,6,8,9],opKinds:OperatorKind[]=['switch','filter','alternator','priority'];const operators=opKinds.map((kind,i)=>({id:i,kind,node:slots[(i+(seed%2))%slots.length],orientation:(seed+i)%3,memory:0}));return{nodes,operators};}
export function createSignalState(seed=1):SignalState{const l=layout(seed);return{seed,time:0,duration:165,nodes:l.nodes,operators:l.operators,packets:[],spawned:0,delivered:0,lost:0,pressure:{},outcome:'playing',nextPacketId:1};}
function opAt(s:SignalState,node:number){return s.operators.find(o=>o.node===node);}
function chooseNext(s:SignalState,p:Packet):number|null{const n=s.nodes[p.node];if(n.sink)return null;let c=n.links.filter(x=>x!==p.from);if(!c.length)c=n.links;if(!c.length)return null;const op=opAt(s,p.node);if(!op)return c[(p.id+p.kind.length)%c.length];if(op.kind==='switch')return c[op.orientation%c.length];if(op.kind==='alternator'){const v=c[op.memory%c.length];op.memory=(op.memory+1)%c.length;return v;}if(op.kind==='filter'){const match=kinds[op.orientation%3]===p.kind;return c[match?0:Math.min(1,c.length-1)];}const congestion=(x:number)=>s.packets.filter(q=>q.node===x&&q.progress<.2).length;return [...c].sort((a,b)=>congestion(a)-congestion(b))[0];}
function spawn(s:SignalState){const wave=Math.floor(s.time/18),interval=Math.max(2.7,5.1-wave*.22),target=Math.floor(s.time/interval);while(s.spawned<target&&s.time<s.duration-18){const kind=kinds[(s.spawned*2+s.seed+wave)%3],source=s.nodes.find(n=>n.source===kind)!;const p:Packet={id:s.nextPacketId++,kind,node:source.id,from:null,next:null,progress:0,wait:0};p.next=chooseNext(s,p);s.packets.push(p);s.spawned++;}}
export function moveOperator(s:SignalState,operatorId:number,nodeId:number){if(s.outcome!=='playing')return false;const op=s.operators.find(o=>o.id===operatorId),node=s.nodes[nodeId];if(!op||!node||node.source||node.sink||node.links.length<2||s.operators.some(o=>o.id!==operatorId&&o.node===nodeId))return false;op.node=nodeId;return true;}
export function rotateOperator(s:SignalState,operatorId:number){const op=s.operators.find(o=>o.id===operatorId);if(op&&s.outcome==='playing')op.orientation=(op.orientation+1)%3;}
export function stepSignal(s:SignalState,dt:number){if(s.outcome!=='playing')return s;s.time+=dt;spawn(s);for(const p of [...s.packets]){if(p.next===null){const sink=s.nodes[p.node].sink;if(sink){sink===p.kind?s.delivered++:s.lost++;s.packets.splice(s.packets.indexOf(p),1);}continue;}const crowd=s.packets.filter(q=>q!==p&&q.node===p.next&&q.progress<.35).length;if(crowd>=2){p.wait+=dt;continue;}p.wait=Math.max(0,p.wait-dt*.5);p.progress+=dt*.38;if(p.progress>=1){p.from=p.node;p.node=p.next;p.progress=0;p.next=chooseNext(s,p);}}const pressure:Record<number,number>={};for(const p of s.packets)pressure[p.node]=(pressure[p.node]??0)+(p.wait>0?1.4:1);s.pressure=pressure;const max=Math.max(0,...Object.values(pressure));if(max>=6||s.lost>=7)s.outcome='lost';else if(s.time>=s.duration)s.outcome=s.delivered>=Math.max(12,s.spawned-5)?'won':'lost';return s;}
export function cloneSignal(s:SignalState):SignalState{return JSON.parse(JSON.stringify(s));}
