import { neighboursOf,type Agent,type Cell,type CellId,type WorldState } from '../world/model';
export type WorldAction={type:'RAISE_CELL';cellId:CellId};
export type WorldEvent={type:'TERRAIN_CHANGED';cellIds:CellId[]}|{type:'AGENT_MOVED';agentId:Agent['id'];from:CellId;to:CellId}|{type:'AGENT_CHARGED';agentId:Agent['id'];element:'water';cellId:CellId}|{type:'CELL_BLOOMED';agentId:Agent['id'];cellId:CellId}|{type:'AGENT_ARRIVED';agentId:Agent['id'];cellId:CellId};export interface SimulationResult{state:WorldState;events:WorldEvent[]}
const MAX_HEIGHT=2.4,MIN_HEIGHT=.08,CLIMB_LIMIT=.16,BLOOM_LIFT=.24,SCULPT_LIFT=.40;
export function simulate(world:WorldState,action:WorldAction):SimulationResult{if(action.type!=='RAISE_CELL'||!world.cells[action.cellId])return{state:world,events:[]};const cells=Object.fromEntries(Object.entries(world.cells).map(([id,c])=>[id,{...c}])) as WorldState['cells'],changed=new Set<CellId>(),target=cells[action.cellId],ns=neighboursOf(world,action.cellId),requested=Math.min(SCULPT_LIFT,MAX_HEIGHT-target.height);if(ns.length&&requested>0){const drains=ns.map(n=>Math.max(0,Math.min(requested/ns.length,cells[n.id].height-MIN_HEIGHT))),total=drains.reduce((s,a)=>s+a,0);if(total>0){target.height+=total;changed.add(target.id);ns.forEach((n,i)=>{if(drains[i]>0){cells[n.id].height-=drains[i];changed.add(n.id);}});}}
 const next:WorldState={...world,cells,agents:world.agents.map(a=>({...a}))},events:WorldEvent[]=[],intents=new Map<Agent['id'],CellId>();for(const a of next.agents){if(a.arrived)continue;const path=findPath(next,a.cellId,a.targetId);if(path.length>1)intents.set(a.id,path[1]);}for(const a of next.agents){const to=intents.get(a.id);if(!to)continue;const from=a.cellId;a.cellId=to;events.push({type:'AGENT_MOVED',agentId:a.id,from,to});}
 for(const a of [...next.agents].sort((x,y)=>x.id.localeCompare(y.id))){const c=next.cells[a.cellId];if(c.id===a.targetId&&!a.arrived){a.arrived=true;events.push({type:'AGENT_ARRIVED',agentId:a.id,cellId:c.id});}if((c.kind==='water-source'||c.kind==='spring')&&a.carrying!=='water'){a.carrying='water';events.push({type:'AGENT_CHARGED',agentId:a.id,element:'water',cellId:c.id});continue;}if(c.kind==='seed'&&a.carrying==='water'){c.kind='bloom';c.height=Math.min(MAX_HEIGHT,c.height+BLOOM_LIFT);a.carrying=null;changed.add(c.id);events.push({type:'CELL_BLOOMED',agentId:a.id,cellId:c.id});}}
 events.unshift({type:'TERRAIN_CHANGED',cellIds:[...changed]});return{state:next,events};}
function findPath(world:WorldState,start:CellId,goal:CellId):CellId[]{if(start===goal)return[start];const frontier:CellId[]=[start],came=new Map<CellId,CellId|null>([[start,null]]);while(frontier.length){frontier.sort((a,b)=>heuristic(world.cells[a],world.cells[goal])-heuristic(world.cells[b],world.cells[goal])||a.localeCompare(b));const current=frontier.shift()!;if(current===goal)break;const cc=world.cells[current];for(const n of neighboursOf(world,current).filter(n=>n.height<=cc.height+CLIMB_LIMIT).sort((a,b)=>heuristic(a,world.cells[goal])-heuristic(b,world.cells[goal])||a.id.localeCompare(b.id))){if(came.has(n.id))continue;came.set(n.id,current);frontier.push(n.id);}}if(!came.has(goal))return[start];const path:CellId[]=[];let cursor:CellId|null=goal;while(cursor!==null){path.unshift(cursor);cursor=came.get(cursor)??null;}return path;}
function heuristic(a:Cell,b:Cell):number{return Math.abs(a.row-b.row)+Math.abs(a.col-b.col)+a.height*.08;}
