import { describe, expect, it } from 'vitest';
import { simulate } from '../src/simulation/simulate';
import { cellId, createInitialWorld } from '../src/world/model';
describe('terrain simulation',()=>{
 it('redistributes matter without mutating input',()=>{const w=createInitialWorld(3,3),t=cellId(1,1),n=cellId(1,0),bt=w.cells[t].height,bn=w.cells[n].height,bm=Object.values(w.cells).reduce((s,c)=>s+c.height,0)/9,r=simulate(w,{type:'RAISE_CELL',cellId:t}),am=Object.values(r.state.cells).reduce((s,c)=>s+c.height,0)/9;expect(w.cells[t].height).toBe(bt);expect(r.state.cells[t].height).toBeCloseTo(bt+.4);expect(r.state.cells[n].height).toBeCloseTo(bn-.1);expect(am).toBeCloseTo(bm,10);});
 it('takes a traversable direct step toward the haven',()=>{const w=createInitialWorld(5,5),a=w.agents[0],s=cellId(2,2);a.cellId=s;a.targetId=cellId(0,2);a.arrived=false;for(const c of Object.values(w.cells))c.height=.7;const r=simulate(w,{type:'RAISE_CELL',cellId:cellId(4,4)});expect(r.state.agents[0].cellId).toBe(cellId(1,2));});
 it('detours around a steep ridge instead of freezing',()=>{const w=createInitialWorld(5,5),a=w.agents[0],s=cellId(2,2);a.cellId=s;a.targetId=cellId(0,2);a.arrived=false;for(const c of Object.values(w.cells))c.height=.5;w.cells[cellId(1,2)].height=1.2;const r=simulate(w,{type:'RAISE_CELL',cellId:cellId(4,4)});expect(r.state.agents[0].cellId).not.toBe(s);expect(r.state.agents[0].cellId).not.toBe(cellId(1,2));});
 it('can make one sculpture affect two motes differently',()=>{const w=createInitialWorld(5,5);for(const c of Object.values(w.cells))c.height=.5;const a=w.agents[0],b=w.agents[1];a.cellId=cellId(3,1);a.targetId=cellId(0,1);a.arrived=false;b.cellId=cellId(3,3);b.targetId=cellId(0,3);b.arrived=false;const r=simulate(w,{type:'RAISE_CELL',cellId:cellId(2,1)});expect(r.state.agents[0].cellId).not.toBe(cellId(2,1));expect(r.state.agents[1].cellId).toBe(cellId(2,3));});
 it('marks arrival',()=>{const w=createInitialWorld(5,5),a=w.agents[0],g=cellId(1,2),s=cellId(2,2);a.cellId=s;a.targetId=g;a.arrived=false;for(const c of Object.values(w.cells))c.height=.7;const r=simulate(w,{type:'RAISE_CELL',cellId:cellId(4,4)});expect(r.state.agents[0].cellId).toBe(g);expect(r.state.agents[0].arrived).toBe(true);});
 it('keeps movement independent of agent array order',()=>{const make=()=>{const w=createInitialWorld(6,6);for(const c of Object.values(w.cells))c.height=.6;w.agents[0].cellId=cellId(3,2);w.agents[0].targetId=cellId(1,2);w.agents[1].cellId=cellId(3,3);w.agents[1].targetId=cellId(1,3);w.agents[2].cellId=cellId(5,0);w.agents[2].targetId=cellId(5,5);for(const a of w.agents)a.arrived=false;return w;},a=make(),b=make();b.agents.reverse();const ra=simulate(a,{type:'RAISE_CELL',cellId:cellId(0,0)}),rb=simulate(b,{type:'RAISE_CELL',cellId:cellId(0,0)}),pos=(r:ReturnType<typeof simulate>)=>Object.fromEntries(r.state.agents.map(x=>[x.id,x.cellId]));expect(pos(ra)).toEqual(pos(rb));});
});
