import{describe,expect,it}from'vitest';import{simulate}from'../src/simulation/simulate';import{cellId,createInitialWorld,type WorldState}from'../src/world/model';
const flat=(rows=7,cols=7)=>{const w=createInitialWorld(rows,cols);for(const c of Object.values(w.cells)){c.height=.5;c.kind='ground'}for(const a of w.agents){a.carrying=null;a.arrived=false}return w};
const step=(w:WorldState,id=cellId(6,6))=>simulate(w,{type:'RAISE_CELL',cellId:id});
const compromiseWorld=()=>{const w=flat(),a=w.agents[0],b=w.agents[1];a.cellId=cellId(4,2);a.targetId=cellId(1,2);b.cellId=cellId(4,3);b.targetId=cellId(1,3);w.cells[cellId(3,2)].height=.68;w.cells[cellId(3,3)].kind='spring';return w};
describe('terrain simulation',()=>{
 it('redistributes matter without mutating input',()=>{const w=createInitialWorld(3,3),t=cellId(1,1),n=cellId(1,0),bt=w.cells[t].height,bn=w.cells[n].height,bm=Object.values(w.cells).reduce((s,c)=>s+c.height,0)/9,r=simulate(w,{type:'RAISE_CELL',cellId:t}),am=Object.values(r.state.cells).reduce((s,c)=>s+c.height,0)/9;expect(w.cells[t].height).toBe(bt);expect(r.state.cells[t].height).toBeCloseTo(bt+.4);expect(r.state.cells[n].height).toBeCloseTo(bn-.1);expect(am).toBeCloseTo(bm,10)});
 it('EXP-013b: one sculpture opens A direct route while closing B direct route',()=>{const w=compromiseWorld(),r=simulate(w,{type:'RAISE_CELL',cellId:cellId(3,3)});expect(r.state.agents[0].cellId).toBe(cellId(3,2));expect(r.state.agents[1].cellId).not.toBe(cellId(3,3))});
 it('EXP-014: a useful detour can collect water then create future terrain',()=>{let w=flat();const a=w.agents[0];a.cellId=cellId(4,2);a.targetId=cellId(0,2);w.cells[cellId(3,2)].kind='spring';w.cells[cellId(2,2)].kind='seed';let r=step(w);expect(r.state.agents[0].carrying).toBe('water');r=step(r.state);expect(r.state.cells[cellId(2,2)].kind).toBe('bloom');expect(r.state.cells[cellId(2,2)].height).toBeGreaterThan(.5)});
 it('EXP-015: growth can become a later route cost for another mote',()=>{let w=flat();const a=w.agents[0],b=w.agents[1];a.cellId=cellId(3,2);a.targetId=cellId(0,2);a.carrying='water';b.cellId=cellId(2,3);b.targetId=cellId(2,0);w.cells[cellId(2,2)].kind='seed';let r=step(w);expect(r.state.cells[cellId(2,2)].kind).toBe('bloom');const bBefore=r.state.agents[1].cellId;r=step(r.state);expect(r.state.agents[1].cellId).not.toBe(cellId(2,2));expect(r.state.agents[1].cellId).not.toBe(bBefore)});
 it('EXP-016: A growth can reroute B through a spring and create reciprocal potential',()=>{let w=flat();const a=w.agents[0],b=w.agents[1];a.cellId=cellId(3,2);a.targetId=cellId(0,2);a.carrying='water';b.cellId=cellId(2,3);b.targetId=cellId(2,0);w.cells[cellId(2,2)].kind='seed';w.cells[cellId(3,3)].kind='spring';let r=step(w);expect(r.state.cells[cellId(2,2)].kind).toBe('bloom');r=step(r.state);expect(r.state.agents[1].cellId).toBe(cellId(3,3));expect(r.state.agents[1].carrying).toBe('water')});
 it('EXP-017: two valid gestures optimize incompatible interests',()=>{const favorA=simulate(compromiseWorld(),{type:'RAISE_CELL',cellId:cellId(3,3)}),favorB=simulate(compromiseWorld(),{type:'RAISE_CELL',cellId:cellId(6,6)});expect(favorA.state.agents[0].cellId).toBe(cellId(3,2));expect(favorA.state.agents[1].carrying).toBe(null);expect(favorB.state.agents[0].cellId).not.toBe(cellId(3,2));expect(favorB.state.agents[1].cellId).toBe(cellId(3,3));expect(favorB.state.agents[1].carrying).toBe('water')});
 it('keeps movement independent of agent array order',()=>{const make=()=>{const w=flat(6,6);w.agents[0].cellId=cellId(3,2);w.agents[0].targetId=cellId(1,2);w.agents[1].cellId=cellId(3,3);w.agents[1].targetId=cellId(1,3);w.agents[2].cellId=cellId(5,0);w.agents[2].targetId=cellId(5,5);return w},a=make(),b=make();b.agents.reverse();const ra=simulate(a,{type:'RAISE_CELL',cellId:cellId(0,0)}),rb=simulate(b,{type:'RAISE_CELL',cellId:cellId(0,0)}),pos=(r:ReturnType<typeof simulate>)=>Object.fromEntries(r.state.agents.map(x=>[x.id,x.cellId]));expect(pos(ra)).toEqual(pos(rb))})});
