import Phaser from 'phaser';
import './style.css';
import { WorldScene } from './presentation/WorldScene';
import { TrajectoryScene } from './presentation/TrajectoryScene';
import { TensionScene } from './presentation/TensionScene';
import { CascadeScene } from './presentation/CascadeScene';
import { ThresholdScene } from './presentation/ThresholdScene';
import { TransferScene } from './presentation/TransferScene';
import { DiscoveryScene } from './presentation/DiscoveryScene';
import { GlobalPressureScene } from './presentation/GlobalPressureScene';
import { VoluntaryRiskScene } from './presentation/VoluntaryRiskScene';
import { PersistentJourneyScene } from './presentation/PersistentJourneyScene';
import { GrowingReachScene } from './presentation/GrowingReachScene';
import { SelfAuthoredArtifactScene } from './presentation/SelfAuthoredArtifactScene';
import { GuidedFlowScene } from './presentation/GuidedFlowScene';
import { ConflictingFlowScene } from './presentation/ConflictingFlowScene';
import { LivingWatershedScene } from './presentation/LivingWatershedScene';
import { SignalScene } from './presentation/SignalScene';
const params=new URLSearchParams(window.location.search),game=params.get('game'),probe=params.get('probe');
const scene=game==='signal'?SignalScene:game==='living-watershed'?LivingWatershedScene:probe==='trajectory'?TrajectoryScene:probe==='tension'?TensionScene:probe==='cascade'?CascadeScene:probe==='threshold'?ThresholdScene:probe==='transfer'?TransferScene:probe==='discovery'?DiscoveryScene:probe==='global-pressure'?GlobalPressureScene:probe==='voluntary-risk'?VoluntaryRiskScene:probe==='persistent-journey'?PersistentJourneyScene:probe==='growing-reach'?GrowingReachScene:probe==='self-authored-artifact'?SelfAuthoredArtifactScene:probe==='guided-flow'?GuidedFlowScene:probe==='conflicting-flow'?ConflictingFlowScene:WorldScene;
new Phaser.Game({type:Phaser.AUTO,parent:'app',width:390,height:760,backgroundColor:'#09151d',scene:[scene],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false}});
